language: node_js
sudo: false
node_js:
  - 8

cache:
  directories:
    - ~/.npm
    - travis_phantomjs
    - travis_ringojs

env:
  global:
    - BIN=node

  matrix:
    -
    - BIN=phantomjs
    - BIN=ringo

matrix:
  include:
    - node_js: 4
      env:
    - node_js: 6
      env:

git:
  depth: 10

branches:
  only:
    - master

before_install:
  # Upgrade PhantomJS.
  - |
      export PHANTOMJS_VERSION=2.1.1
      export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
      if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
        rm -rf $PWD/travis_phantomjs
        mkdir -p $PWD/travis_phantomjs
        wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
        tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
      fi
      phantomjs -v

  # Install RingoJS.
  - |
      export RINGOJS_VERSION=1.2.1
      export PATH=$PWD/travis_ringojs/ringojs-$RINGOJS_VERSION/bin:$PATH
      if [ ! -f "$(which ringo)" ] || [ $(ringo --version | grep -Eo '[0-9.]+') != $RINGOJS_VERSION ]; then
        rm -rf $PWD/travis_ringojs
        mkdir -p $PWD/travis_ringojs
        wget https://github.com/ringo/ringojs/releases/download/v$RINGOJS_VERSION/ringojs-$RINGOJS_VERSION.tar.gz
        tar -xvf ringojs-$RINGOJS_VERSION.tar.gz -C $PWD/travis_ringojs
      fi
      ringo -v

  - nvm use $TRAVIS_NODE_VERSION
  - npm i -g npm@^5

install:
  - npm i

script:
  - cd test
  - $BIN ./test.js
